WITH SALE AS (
    SELECT
        BOOK_ID,
        SUM(SALES) AS SALES
    FROM
        BOOK_SALES 
    WHERE
        SALES_DATE LIKE '2022-01%'
    GROUP BY
        BOOK_ID
)
SELECT 
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM 
    SALE S
JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID 
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY
ORDER BY
    A.AUTHOR_ID,
    B.CATEGORY DESC