SELECT 
    B.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B 
    ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR A 
    ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE 
    BS.SALES_DATE LIKE '2022-01%'
GROUP BY 
    B.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY
ORDER BY 
    B.AUTHOR_ID, 
    B.CATEGORY DESC