SELECT
    P.PRODUCT_CODE,
    PM.SALES_AMOUNT * P.PRICE AS SALES
FROM (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM
        OFFLINE_SALE
    GROUP BY
        PRODUCT_ID
) PM
JOIN
    PRODUCT P
ON 
    PM.PRODUCT_ID = P.PRODUCT_ID
ORDER BY
    SALES DESC,
    P.PRODUCT_CODE ASC
# SELECT * FROM OFFLINE_SALE WHERE PRODUCT_ID = '2'