SELECT 
    CCR.CAR_ID AS CAR_ID,
    CCR.CAR_TYPE AS CAR_TYPE,
    FLOOR(CCR.DAILY_FEE * 30 * (1 - CCDP.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CCR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CCDP ON CCR.CAR_TYPE = CCDP.CAR_TYPE AND CCDP.DURATION_TYPE = '30일 이상'
WHERE (CCR.CAR_TYPE = '세단' OR CCR.CAR_TYPE = 'SUV') 
    AND CCR.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
GROUP BY CCR.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID 