
SELECT
     CC.CAR_ID,
     CC.CAR_TYPE,
     FLOOR(CC.DAILY_FEE * 30 * (1 - CP.DISCOUNT_RATE / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR CC
LEFT JOIN 
    (SELECT 
        CAR_ID, 
        MIN(START_DATE) AS START_DATE, 
        MAX(END_DATE) AS END_DATE 
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    GROUP BY 
        CAR_ID) CH 
ON 
    CC.CAR_ID = CH.CAR_ID
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
ON 
    CP.CAR_TYPE = CC.CAR_TYPE AND CP.DURATION_TYPE = '30일 이상'
WHERE
    CC.CAR_TYPE IN ('SUV', '세단') AND
    (
        CH.CAR_ID IS NULL OR
        CH.END_DATE < '2022-11-01' OR CH.START_DATE > '2022-11-30'
    ) 
    AND FLOOR(CC.DAILY_FEE * 30 * (1 - CP.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 2000000
GROUP BY
    CH.CAR_ID
ORDER BY
    FEE DESC,
    CC.CAR_TYPE ASC,
    CC.CAR_ID DESC
    