SELECT
    F.FOOD_TYPE,
    F.REST_ID,
    F.REST_NAME,
    F.FAVORITES
FROM
    REST_INFO F
JOIN (
    SELECT
        FOOD_TYPE,
        REST_ID,
        REST_NAME,
        MAX(FAVORITES) AS FAVORITES
    FROM 
        REST_INFO
    GROUP BY
        FOOD_TYPE
) F2 ON F.FOOD_TYPE = F2.FOOD_TYPE AND F.FAVORITES = F2.FAVORITES
ORDER BY
FOOD_TYPE DESC