SELECT
    UU.USER_ID,
    UU.NICKNAME,
    CONCAT(UU.CITY, ' ', UU.STREET_ADDRESS1, ' ', UU.STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTRING(UU.TLNO, 1, 3), '-', SUBSTRING(UU.TLNO, 4, 4), '-', SUBSTRING(UU.TLNO, 8, 4)) AS '전화번호'
    # UU.*
FROM (
    SELECT
        *,
        COUNT(WRITER_ID) AS COUNT
    FROM 
        USED_GOODS_BOARD
    GROUP BY
        WRITER_ID
    HAVING
        COUNT >= 3
       
) UG
JOIN
    USED_GOODS_USER UU
ON
    UG.WRITER_ID = UU.USER_ID
ORDER BY
    UU.USER_ID DESC
