SELECT 
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    UI.GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS
FROM 
    ONLINE_SALE OS
JOIN 
    USER_INFO UI ON UI.USER_ID = OS.USER_ID
WHERE
    UI.GENDER IS NOT NULL
GROUP BY
    YEAR,
    MONTH,
    UI.GENDER
ORDER BY
    YEAR ASC,
    MONTH ASC,
    UI.GENDER ASC