-- 코드를 입력하세요

WITH FORMAT_USER_INFO AS (
    SELECT
    * 
    FROM
        USER_INFO
    WHERE GENDER IS NOT NULL
)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    UI.GENDER AS GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USER
FROM
    ONLINE_SALE OS
JOIN FORMAT_USER_INFO UI ON OS.USER_ID = UI.USER_ID
GROUP BY
    YEAR(SALES_DATE),
    MONTH(SALES_DATE),
    UI.GENDER
ORDER BY
    YEAR(SALES_DATE),
    MONTH(SALES_DATE),
    UI.GENDER