WITH SUBWAY AS (
    SELECT
        ROUTE,
        SUM(D_BETWEEN_DIST) AS SUM,
        COUNT(LINE) AS COUNT
    FROM SUBWAY_DISTANCE
    GROUP BY
        ROUTE
    ORDER BY
        SUM DESC
)
SELECT
    S.ROUTE AS ROUTE,
    CONCAT(ROUND(S.SUM, 1), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(S.SUM / S.COUNT, 2), 'km') AS AVERAGE_DISTANCE
FROM 
    SUBWAY S
