WITH FISH AS (
    SELECT
        FISH_TYPE,
        COUNT(FISH_TYPE) AS FISH_COUNT
    FROM
        FISH_INFO
    GROUP BY
        FISH_TYPE
)
SELECT
    F.FISH_COUNT,
    FI.FISH_NAME
FROM 
    FISH F
LEFT JOIN 
    FISH_NAME_INFO FI
ON 
    F.FISH_TYPE = FI.FISH_TYPE
ORDER BY 
    FISH_COUNT DESC
    