WITH JOINED AS (
    SELECT
        USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
TOTAL_JOIN AS (
    SELECT
        COUNT(*) AS T_COUNT
    FROM
        JOINED
)


SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / TJ.T_COUNT, 1) AS PUCHASED_RATIO
FROM 
    ONLINE_SALE OS
JOIN JOINED J ON J.USER_ID = OS.USER_ID
CROSS JOIN TOTAL_JOIN TJ
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH