WITH RECURSIVE GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA ED
    JOIN GENERATION G ON G.ID = ED.PARENT_ID
)

SELECT COUNT(*) AS COUNT, G.GENERATION AS GENERATION 
FROM GENERATION G
LEFT JOIN ECOLI_DATA ED ON G.ID = ED.PARENT_ID
WHERE ED.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC