-- 코드를 입력하세요
SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    FP.PRICE * FO.AMOUNT AS TOTAL_SALES
FROM
    FOOD_PRODUCT FP
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT FROM FOOD_ORDER WHERE PRODUCE_DATE LIKE '2022-05%' GROUP BY PRODUCT_ID
) FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY
    3 DESC,
    1
