WITH TRUCK_RENTAL AS (
    SELECT 
        H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DAYS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)
SELECT 
    TR.HISTORY_ID,
    ROUND(
        TR.DAILY_FEE * TR.RENTAL_DAYS * 
        (100 - IFNULL(DP.DISCOUNT_RATE, 0)) / 100
    , 0) AS FEE
FROM TRUCK_RENTAL TR
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON DP.CAR_TYPE = '트럭'
    AND (
        (TR.RENTAL_DAYS >= 90 AND DP.DURATION_TYPE = '90일 이상')
        OR (TR.RENTAL_DAYS >= 30 AND TR.RENTAL_DAYS < 90 AND DP.DURATION_TYPE = '30일 이상')
        OR (TR.RENTAL_DAYS >= 7 AND TR.RENTAL_DAYS < 30 AND DP.DURATION_TYPE = '7일 이상')
    )
ORDER BY FEE DESC, TR.HISTORY_ID DESC;