WITH CAR AS (
    SELECT
        CR.HISTORY_ID,
        CR.CAR_ID,
        CC.CAR_TYPE,
        CC.DAILY_FEE,
        DATEDIFF(CR.END_DATE, CR.START_DATE) + 1 AS TOTAL_DATE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
    JOIN
        CAR_RENTAL_COMPANY_CAR CC
    ON
        CR.CAR_ID = CC.CAR_ID
    WHERE
        CC.CAR_TYPE = '트럭'

), CARS AS (
    SELECT 
        C.HISTORY_ID,
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        C.TOTAL_DATE,
        CASE 
            WHEN C.TOTAL_DATE >= 90 THEN '90일 이상'
            WHEN C.TOTAL_DATE >= 30 THEN '30일 이상'
            WHEN C.TOTAL_DATE >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR C
)

SELECT
    C.HISTORY_ID,
    ROUND(C.TOTAL_DATE * C.DAILY_FEE * (1 - COALESCE(CP.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM
    CARS C
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
ON
    CP.CAR_TYPE = C.CAR_TYPE AND CP.DURATION_TYPE = C.DURATION_TYPE
ORDER BY
    FEE DESC,
    C.HISTORY_ID DESC