WITH APPOINTMENT_CS AS (
    SELECT
        *
    FROM
        APPOINTMENT
    WHERE
        APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YMD IS NULL AND MCDP_CD = 'CS'
)

SELECT
    AC.APNT_NO AS APNT_NO,
    P.PT_NAME,
    P.PT_NO,
    AC.MCDP_CD,
    D.DR_NAME,
    (AC.APNT_YMD) AS APNT_YMD
FROM
    PATIENT P
JOIN
    APPOINTMENT_CS AC ON P.PT_NO = AC.PT_NO
JOIN
    DOCTOR D ON D.DR_ID = AC.MDDR_ID
ORDER BY
    APNT_YMD ASC