WITH RECURSIVE Hour AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1
    FROM Hour
    WHERE HOUR < 23
)

SELECT
    h.HOUR,
    COALESCE(COUNT(A.DATETIME), 0) AS COUNT
FROM 
    Hour h
LEFT JOIN ANIMAL_OUTS A 
    ON h.HOUR = HOUR(A.DATETIME)
GROUP BY
    h.HOUR
ORDER BY
    h.HOUR