SELECT
    UG.USER_ID,
    UG.NICKNAME,
    UB.TOTAL_SALES
FROM
    USED_GOODS_USER UG
JOIN (
    SELECT
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM 
        USED_GOODS_BOARD
    WHERE
        STATUS = 'DONE'
    GROUP BY
        WRITER_ID
    HAVING
        SUM(PRICE) >= 700000
) UB ON UG.USER_ID = UB.WRITER_ID
ORDER BY
    TOTAL_SALES