SELECT
    UG.USER_ID,
    UG.NICKNAME,
    SUM(UB.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD UB
LEFT JOIN USED_GOODS_USER UG ON UB.WRITER_ID = UG.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY
    UG.USER_ID,
    UG.NICKNAME
HAVING
    SUM(UB.PRICE) >= 700000
ORDER BY
    TOTAL_SALES
    