SELECT
    UU.USER_ID,
    UU.NICKNAME,
    UB.PRICE 
FROM USED_GOODS_USER UU
JOIN (
    SELECT
        WRITER_ID,
        SUM(PRICE) AS PRICE
    FROM
        USED_GOODS_BOARD
    WHERE
        STATUS = 'DONE'
    GROUP BY
        WRITER_ID
) UB
ON
    UB.WRITER_ID = UU.USER_ID
WHERE
    UB.PRICE >= 700000
ORDER BY
    UB.PRICE ASC;
    