WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN REVIEW_COUNT RC ON R.MEMBER_ID = RC.MEMBER_ID
JOIN MEMBER_PROFILE M ON M.MEMBER_ID = R.MEMBER_ID
WHERE RC.COUNT = (SELECT MAX(COUNT) FROM REVIEW_COUNT)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;
