WITH COUNT_REVIEW AS (
    SELECT 
        MEMBER_ID,
        COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_COUNT AS (
    SELECT
        MEMBER_ID
    FROM
        COUNT_REVIEW
    WHERE CNT = (SELECT MAX(CNT) FROM COUNT_REVIEW)
)

SELECT 
    MP.MEMBER_NAME AS MEMBER_NAME,
    RR.REVIEW_TEXT AS REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_COUNT)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC