SELECT ED2.ID, ED2.GENOTYPE, ED1.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ED1
LEFT JOIN ECOLI_DATA ED2 ON ED1.ID = ED2.PARENT_ID
WHERE ED2.ID IS NOT NULL 
    AND (ED1.GENOTYPE & ED2.GENOTYPE) = ED1.GENOTYPE
ORDER BY ED2.ID ASC