WITH MAX_COLONY AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE_COLONY, YEAR(DIFFERENTIATION_DATE) AS DATE
    FROM ECOLI_DATA
    GROUP BY DATE
    ORDER BY DATE ASC
)

SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (MC.MAX_SIZE_COLONY - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID AS ID
FROM ECOLI_DATA ED
JOIN MAX_COLONY MC ON MC.DATE = DATE_FORMAT(ED.DIFFERENTIATION_DATE, '%Y')
ORDER BY YEAR ASC, YEAR_DEV ASC