SELECT
    DISTINCT CR.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR CR
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
ON 
    CR.CAR_ID = CH.CAR_ID
WHERE
    MONTH(CH.START_DATE) LIKE '10' AND
    CR.CAR_TYPE = '세단'
ORDER BY
    CR.CAR_ID DESC