WITH RankedEmployees AS (
    SELECT 
        HG.EMP_NO, 
        SUM(HG.SCORE) AS TOTAL_SCORE, 
        RANK() OVER (ORDER BY SUM(HG.SCORE) DESC) AS RANKING
    FROM HR_GRADE HG
    GROUP BY HG.EMP_NO
)
SELECT 
    RE.TOTAL_SCORE AS SCORE,
    RE.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL
FROM RankedEmployees RE
JOIN HR_EMPLOYEES HE
    ON HE.EMP_NO = RE.EMP_NO
WHERE RE.RANKING = 1;