SELECT
    DG.DEPT_ID,
    HD.DEPT_NAME_EN,
    ROUND(DG.TOTAL / DG.TOTAL_COUNT, 0) AS AVG_SAL
FROM (
    SELECT 
        HE.DEPT_ID AS DEPT_ID,
        COUNT(HE.DEPT_ID) AS TOTAL_COUNT,
        SUM(HE.SAL) AS TOTAL
    FROM 
        HR_EMPLOYEES HE
    GROUP BY 
        DEPT_ID
) DG
JOIN 
    HR_DEPARTMENT HD
ON HD.DEPT_ID = DG.DEPT_ID
ORDER BY
    AVG_SAL DESC
    
    