WITH RankFood AS (
    SELECT 
        FP.*,
        ROW_NUMBER() OVER (PARTITION BY FP.CATEGORY ORDER BY FP.PRICE DESC) AS ROW_NUM
    FROM 
        FOOD_PRODUCT FP
    WHERE
        FP.CATEGORY IN ('과자', '국', '김치', '식용유')
    ORDER BY FP.PRICE DESC
)

SELECT R.CATEGORY, R.PRICE AS MAX_PRICE, R.PRODUCT_NAME
FROM RankFood R
WHERE ROW_NUM = 1;