WITH FISH AS (
    SELECT 
        FISH_TYPE, 
        COUNT(FISH_TYPE) AS FISH_COUNT, 
        SUM(COALESCE(LENGTH, 10)) AS SUM,
        MAX(COALESCE(LENGTH, 10)) AS MAX_LENGTH
    FROM 
        FISH_INFO
    GROUP BY 
        FISH_TYPE
)
SELECT 
    F.FISH_COUNT,
    F.MAX_LENGTH,
    F.FISH_TYPE
FROM
    FISH F
WHERE
    F.SUM / F.FISH_COUNT >= 33
ORDER BY 
    F.FISH_TYPE ASC