# -- 코드를 작성해주세요
SELECT
    FISH_COUNT,
    MAX_LENGTH,
    FISH_TYPE
FROM (
    SELECT
        FISH_TYPE,
        FLOOR(SUM(LENGTH) / COUNT(*)) AS LENGTH,
        MAX(LENGTH) AS MAX_LENGTH,
        COUNT(*) AS FISH_COUNT
    FROM
        FISH_INFO
    GROUP BY
        FISH_TYPE
) F
WHERE 
    LENGTH >= 33
ORDER BY
    FISH_TYPE

